create table dwh.reid_journal (
    id integer GENERATED BY DEFAULT AS IDENTITY primary key,
    ts timestamp without time zone NULL,
    cosine double precision NULL,
    filename text,
    best_frame text
);

create table dwh.frames (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reid integer REFERENCES dwh.reid_journal (id),
    came_in timestamp without time zone NULL,
    threshold float(32),
    sharpness float(32),
    rect_id int,
    emotions float(32)[],
    camera_id int,
    object_id int,
    track_id int,
    ages int,
    female_value float(32),
    hash float(32)[],
    best boolean default false
);
